### ISSUE TITLE
Why is this a separate repo?

### ISSUE THREAD

**Issue by Mouthless-Stoat** [ashwinjadhav818/yasb#5]
Why is this a separate repo under a different account and not just a fork under the [original repo](https://github.com/da-rth/yasb/tree/main)? This repo seem like the main one with more commit, but it seem to remove all tie to the original repo or acknowledge it. Shouldn't there be a link somewhere to route back to the original one?

**Comment by shadowash8** [comment]
Hii, 
This fork is not shown as a for as I wanted people to add pull requests and issues directly to my fork, and I actually forgot to add a note to acknowledge the original repo, but there are still mentions of the original dev in the code.
I'll update the README right now
Thank You.
